# Central configuration settings
# used for E2E environment pipelines
variables:

# Resource prefix for this environment
- name:  'prefix'
  value: 'ace2e'          # <===== CHANGE THIS! Must not be longer than 6 characters! Needs to be a unique prefix

- name: 'stampLocations'
  value: '["westeurope"]'    # Check which regions are valid. There is a list in /src/infra/README.md

# Terraform state variables
- name:  'terraformResourceGroup'
  value: 'alwayson-terraformstate-rg'      # <===== CHANGE THIS VALUE IF NEEDED
- name:  'terraformStorageAccount'
  value: '$(prefix)tfstatestore'  # Needs to be a globally unique name

# Other settings
- name:  'contactEmail'
  value: 'noreply@example.com'  # <===== CHANGE THIS VALUE TO ONE OF YOUR REAL EMAIL ADDRESSES (OR A GROUP)!