# cert-manager - Additional K8s configuration manifest file
# Needed config to deploy cert-manager components into its own namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: alwaysonappnet@microsoft.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the DNS-01 challenge provider
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: {{ .Values.azure.subscriptionId | quote }}
            resourceGroupName: {{ .Values.azure.dnsZoneResourceGroupName | quote }}
            hostedZoneName: {{ .Values.azure.dnsZoneName | quote }}
            environment: AzurePublicCloud
            managedIdentity:
              # client id of the node pool managed identity
              clientID: {{ .Values.azure.managedIdentityClientId | quote }}
    # - http01:
    #     ingress:
    #       class: nginx